version: "3.7"
services:

  squid:
    image: ubuntu/squid
    restart: unless-stopped
    network_mode: service:vpn-sidecar
    depends_on:
      - vpn-sidecar

  web-proxy:
    image: dperson/nginx
    restart: unless-stopped
    environment:
      - STREAM=69;squid:3128
    ports:
      - 3128:69/tcp
    links:
      - vpn-sidecar:squid
    depends_on:
      - squid
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    networks:
      - default
      - isolated_vpn_network

  vpn-sidecar:
    image: linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules
      - wgclient-data-volume:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?
    networks:
      - isolated_vpn_network

volumes:
  wgclient-data-volume: # writeable location of wg0.conf
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/wireguard/"

networks:
  default:
  isolated_vpn_network:
